### ISSUE TITLE
Implement additional hooks

### ISSUE THREAD

**Issue by petrbel** [Cognexa/cxflow#111]
Extend the set of hooks by e.g.

- [x] terminate when training is overfitted (this might be a base hook from which additional hooks will be derived (one e.g. terminates))
- [ ] terminate when some of the statistics is NaN

It would be nice to a have a `EveryNEpochs` hook, which would be a base hook. The purpose of this hook is to provide an API which allows its descendants to run some actions every e.g. `N` epochs. Some hooks already does this, to they should be reimplemented.

- [x] `EveryNEpochs`

**Comment by petrbel** [comment]
@gnovis this issue is a top priority, please implement at least basic overfitting detection. Thanks

**Comment by blazekadam** [comment]
Assigning @petrbel as @gnovis is not available for a while. Implement it including tests please. Thanks.
