### ISSUE TITLE
fix, refactor and extend functionality of SaveImage

### ISSUE THREAD

**Issue by MarekSebo** [Cognexa/cxflow#123]
* [ ] Correct example in docstring
* [ ] Change default factor to 255
* [ ] Enable supporting multiple variables (i.e. saving images, masks and predictions)
* [ ] Fix epoch counting when using skip_zeroth_epoch

**Comment by blazekadam** [comment]
This should be in https://github.com/Cognexa/cxblocks, pls move and close this one

**Comment by MarekSebo** [comment]
Moved to cxblocks as issue [#13](https://github.com/Cognexa/cxblocks/issues/13)
