### ISSUE TITLE
refactor LogProfile --> LogDuration?

### ISSUE THREAD

**Issue by MarekSebo** [Cognexa/cxflow#126]
If the hook is not planned to be used for something else than measuring duration of processes, then it would be reasonable to give it a more self describing name LogDuration.

**Comment by blazekadam** [comment]
The hook itself does not measure anything. It just logs the time **profile** which is collected by `MainLoop`, program **profiling** or **profiler** is a common term used in the field for measuring execution times of particular code blocks. See <https://en.wikipedia.org/wiki/Profiling_(computer_programming)>.
