### ISSUE TITLE
Multiple config files support

### ISSUE THREAD

**Issue by gnovis** [Cognexa/cxflow#13]
If we decide we need multiple YAML files that somehow automagically merges, here is a possible solution (but also a nasty dependency) https://github.com/zerwes/hiyapyco

**Comment by blazekadam** [comment]
@petrbel @FloopCZ @adkoadko @bvavrik can you please comment if you consider this feature to be important/missing?

**Comment by FloopCZ** [comment]
So far, I have not required this functionality, so for me, it is not an important missing feature.

**Comment by petrbel** [comment]
I can't image a situation in which I'd need this.

**Comment by bvavrik** [comment]
I am happy with `yaml` as it is as well
