### ISSUE TITLE
Add AppVeyor CI

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow#139]
If we are interested in Windows support, we should test it regularly.

**Comment by blazekadam** [comment]
I tried to set up win CI in branch `win` but AppVeyor is getting stuck at various points (even during `pip install`).

E.g.:
https://ci.appveyor.com/project/blazekadam/cxflow/build/job/3g8jquftrbsmsrf1

They even provide RDP for debugging. I successfully connected to it and run the tests manually... No idea what is wrong with it...

**Comment by blazekadam** [comment]
I 've opened an issue for that http://help.appveyor.com/discussions/problems/8485-job-execution-getting-stuck-at-various-point-non-deterministicly

**Comment by FloopCZ** [comment]
Thank you for solving this. I have used AppVeyor multiple times and I have never encountered such an issue.

**Comment by blazekadam** [comment]
I was unable to troubleshoot the issue with AppVeyor. It may be something with insufficient entropy for random number generators but that is just a hypothesis. We ll re-open this later.
