### ISSUE TITLE
StopOnPlateau hook loss granularity

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxflow#148]
At the moment, `StopOnPlateau` hook works with per-example losses. This is quite surprising to me as I would expect it to work on per-epoch  losses for the following reasons:

- example losses may subject to high variance
- one has to know the number of examples in each epoch for setting appropriate values for `long_term` and `short_term` parameters
- all the other hooks log epoch-level aggregations, it is counter-intuitive and confusing to have this single exception

@FloopCZ @petrbel pls comment

**Comment by FloopCZ** [comment]
I agree with you, it should work on per-epoch losses.

**Comment by blazekadam** [comment]
Also I would like to re-use the plateau detection routine for `ReduceLROnPlateu` etc. Can we implement lets say `OnPlateau` hook with abstract `_on_plateau_action` and derive `StopOnPlateau` hook from it?

**Comment by FloopCZ** [comment]
That sounds like a good idea!

**Comment by gnovis** [comment]
@petrbel what do you think about loss granularity?

**Comment by blazekadam** [comment]
Closed with #153
