### ISSUE TITLE
Ensembles

### ISSUE THREAD

**Issue by gnovis** [Cognexa/cxflow#15]
Research the possibility of having `cxflow ensemble` subcommand that would merge multiple computationals graph into one and dumping a regular checkpoint.

@petrbel :
Just to sum up the discussion we had last week
- we need to benchmark few nets (various number of params, rnn/cnn, ..) in order to determine how fast/slow is the
   - decoding the network from file
   - loading the network to the GPU
- then we should determine whether manualy force the computational graphs to merge somehow or simple evaluate multiple networks serially

I prefer the later option, hence I suggest creating both cxtream and fuel NetApplier of EnsembleApplier.

**Comment by blazekadam** [comment]
This is in fact back-end specific. I suggest to move this issue to cxflow-tensorflow repo. Any objections @FloopCZ @petrbe l?

**Comment by petrbel** [comment]
> I prefer the later option

Me too. Merging the TF graphs isn't that easy.

> This is in fact back-end specific.

Is it? I think we want `cxflow ensemble` command regardless the backend. However, the TF implementation obviously belongs to TF. So whatever :)

**Comment by FloopCZ** [comment]
You both are right. I believe that implementation is backend specific and interface is backend agnostic. So I agree with @red that this should be moved.

**Comment by blazekadam** [comment]
Well I can imagine `cxflow predict --ensemble` which would take a list of configs/dirs instead of a single one. The question is how to actually implement the ensembling. Averaging? Majority voting? And how to determine what should be ensembled, i.e. which variable is the actual prediction.
