### ISSUE TITLE
Hook tests

### ISSUE THREAD

**Issue by gnovis** [Cognexa/cxflow#16]
* [x]  **SigintHook**
* [x]  **EpochStopperHook**
* [x]  **AccumulatinHook**
* [x]  **CSVHook**
* [x]  **Stats**
* [x]  **TrainCheckHook**
* [x]  **SaverHook**

To be not tested:
- **LoggingHok**
- **AbstractHook**

**Comment by blazekadam** [comment]
Removed TensorBoardHook as it is no longer present.

**Comment by petrbel** [comment]
@gnovis is this finished?

**Comment by gnovis** [comment]
@petrbel Yes.

**Comment by blazekadam** [comment]
Re-opening as the `LoggingHook` (soon to be `LogVariables` hook) is not tested yet. 

It is one of the commonly utilized hooks; hence, it shall be tested. See `ProfileHook` (soon to be `LogProfile` hook) for an example for log testing.

**Comment by blazekadam** [comment]
Try using https://coverage.readthedocs.io/en/coverage-4.4.1/ to check if the tests are complete.

**Comment by blazekadam** [comment]
@gnovis would you mind writing the test for the `LoggingHook`~`LogVariables` hook?

**Comment by gnovis** [comment]
Sure, I think I can manage it.

**Comment by blazekadam** [comment]
This is actually closed with #105
