### ISSUE TITLE
Log dirs created by cxflow are inaccesible for group and others

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxflow#170]
By default, cxflow log dirs are created with
```
drwx------
```

Imo, it should be
```
drwxr-xr-x
```

Pls comment @FloopCZ, @petrbel ?

**Comment by blazekadam** [comment]
It is because it is created as a temp. dir with
```
tempfile.mkdtemp(...)
```

**Comment by FloopCZ** [comment]
You are very right, it should follow the user's mask.

**Comment by petrbel** [comment]
btw fun python note at [SO](https://stackoverflow.com/questions/7150826/how-can-i-get-the-default-file-permissions-in-python)

> There is a function umask in the os module. You cannot get the current umask per se, you have to set it and the function returns the previous setting.

**Comment by blazekadam** [comment]
No need for getting the current mask. `os.mkdir` will do it for you.
