### ISSUE TITLE
DownloadDataset from direct URLs

### ISSUE THREAD

**Issue by petrbel** [Cognexa/cxflow#178]
I suggest removing `url_root` and refactoring `download_filenames` to `download_urls` so that it contains a list of full URLs. The current implementation forces the user to have all to-be-downloaded files in a single directory on a single server (URL).

This is too restricting as sometimes one wants to download resources from various URLs (e.g. pretrained embeddings from facebook site, dataset from cluster, token dictionary from github etc).

**Comment by blazekadam** [comment]
+1
