### ISSUE TITLE
Implement standard networks

### ISSUE THREAD

**Issue by gnovis** [Cognexa/cxflow#18]
Whishlist
* [ ]  Inception v?
* [ ]  ResNet
* [ ]  faster/segment/whataver R-CNN 
* [ ]  OdoNet (CNN MLP LSTM CTC)
* [ ]  Conv autoencoder with skip connections

Petr: I suggest investing some time by looking at [tensorflow/models](https://github.com/tensorflow/models) - there are many models already implemented (under Apache License 2.0) and I think they could be easily ported to cxflow.

**Comment by blazekadam** [comment]
Adding v.1.0.0. milestone as this is definitely must have in the 1st release. The question is how to include the examples. We need the examples in this repo yet a back-end would be required for that...

**Comment by petrbel** [comment]
I propose creating a new repo, e.g. Cognexa/cxflow-examples which would consists of multiple directories. Each directory would contain a working example with own readme and requirements.

I propose linking this repo from main cxflow repo and also other major plugins (such as cxflow-tensorflow).
We could even make it a submodule, but I don't think we need that.

**Comment by blazekadam** [comment]
New repo `cxflow-examples` is set up. Closing this issue here, please open per-model issues there if you wish.
