### ISSUE TITLE
Main loop empty batch behavior

### ISSUE THREAD

**Issue by petrbel** [Cognexa/cxflow#188]
Main loop should be configurable for cases of empty batches. I suggest the following:

1. Main loop checks the actual batch size
2. In the case of empty batch, acts accordingly to the configuration
    - `ignore` fetches another batch
    - `warn` prints a warning mesage but keep processing this (empty) batch
    - `error` prints an error message and terminates the whole training

**Comment by blazekadam** [comment]
- we can handle `error` just by raising `ValueError` (it effectively stops the training and prints the error)
- we should detect and raise an error on empty stream as well (i.e. no batches or empty batches only)

**Comment by blazekadam** [comment]
Btw, I am not sure if we agree on what is actually an *empty batch*. It is clear than an empty dict (`{}`) is indeed an empty batch. Can we check for anything else?

**Comment by petrbel** [comment]
I think an empty batch is also a batch with zero elements in the sources.

E.g.
```
{
"ids": [],
"images": [],
"masks": [],
}
```

In these cases, I'd check one source for emptyness and assume that the others match.

**Comment by FloopCZ** [comment]
@petrbel :+1: this is what `cxtream` empty batch looks like. I don't believe that `{}` should even be allowed, having the keys always there makes the code simpler.
