### ISSUE TITLE
Reimplement ensemble majority vote

### ISSUE THREAD

**Issue by petrbel** [Cognexa/cxflow#208]
The current implementation is pretty slow. I suggest experimenting with [this SO answer](https://stackoverflow.com/a/6252400) (use `numpy` instead of `Counter`).

The only limitation is that only non-negative integers are supported, however, we can always check this condition and fallback to `Counter`.

Related file: https://github.com/Cognexa/cxflow/blob/dev/cxflow/models/ensemble_model.py

**Comment by blazekadam** [comment]
`np` should be indeed faster

```
➜ red@red ~  
python -m timeit 'import numpy as np;from collections import Counter;Counter(np.random.randint(0,100,1000)).most_common();' 
10000 loops, best of 3: 128 usec per loop
➜ red@red ~  
python -m timeit 'import numpy as np;from collections import Counter;np.argmax(np.bincount(np.random.randint(0,100,1000)));'
100000 loops, best of 3: 11.6 usec per loop
```

**Comment by blazekadam** [comment]
On the other hand:
- `np.bincount` is limited to 1-dim integer arrays
- we can expect millions (of examples) x units (of models) x tens (of classes) hence one call of the `major_vote` function would be on a quite small object, i.e. the following measurement fits better

```

**Comment by blazekadam** [comment]
@petrbel I would suggest closing this issue. I do not think we can speed it up significantly. The major vote aggregation is simply not suitable for a large amount of *examples* (pixels in your case). Btw, 10 Isletnet images have roughly 30M millions of pixels (examples).

**Comment by petrbel** [comment]
ok, closing
