### ISSUE TITLE
Create documentation and tutorials

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxflow#45]
Progress

- [X] write tutorial
- [x] write advanced setion
- [x] polish API
- [x] create cxflow-examples repository with working and tested examples

**Comment by FloopCZ** [comment]
There is a `doc` branch, where the now documentation is being created. Feel free to contribute.

**Comment by petrbel** [comment]
I added few lines yesterday. After some polish and proofreading, I think the main tutorial is finished. However, the advanced stuff are still incomplete.

**Comment by blazekadam** [comment]
Closing as doc was merged to dev.
