### ISSUE TITLE
Remove config nesting in dataset constructor

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxflow#52]
At the moment, the dataset configuration is nested in `dataset` namespace e.g. `dataset.batch_size` although there is no other top-level namespace.

This redundant nesting should be remove to easy access to the configuration.

**Comment by petrbel** [comment]
@gnovis please let me know when you start working on this. Maybe it would be better to fork `resume` branch instead of `dev` as there are many changes... Or maybe it will be merged by that time.

**Comment by blazekadam** [comment]
I just realized what was the reason for nesting. There is actually another top-level entry, `log_dir` in particular.

I would make it flat anyway. Just throw an Exception if the config contains `dataset.log_dir` as it is a reserved name.

I do not think that we need to synchronize the work here. There will be like 3 lanes of diff. Any conflicts may be easily resolved later on.
