### ISSUE TITLE
SIGINT hook does not allow to kill dataset constructor

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow#63]
SIGINT hook traps signals before dataset construction and processes it after it. If dataset construction takes too long, it does not allow to kill it by Ctrl+C. An expected behavior would be to start trapping signals before training.

**Comment by blazekadam** [comment]
Good point. It can not be handle with a hook though. This must be resolved directly in cxflow right?

**Comment by FloopCZ** [comment]
It should be doable by a hook. Actually, I am not sure why is it happening, since sigint hook registers the handler in `before_training` function, which should be launched after the dataset is created. I will have to diagnose deeper.

**Comment by petrbel** [comment]
similar problem with dataset methods

**Comment by FloopCZ** [comment]
Well, I don't think we can solve it for other dataset methods than constructor, because if we want to terminate gracefully and the dataset is already doing something in the middle of the training, we have to wait for it. I am not sure how to solve it. It may be possible to call e.g.t, dataset's terminate() function or to forward the SIGINT. However, the implementation of the dataset would complicate somehow.

**Comment by blazekadam** [comment]
I am strongly against yet another enforced method. Just kill the damn thing! :)

**Comment by blazekadam** [comment]
What is the status? Do we want to take some action before we merge #157 ?

**Comment by FloopCZ** [comment]
I believe that in #157 will partially solve the issue. Unfortunately, the problem of killing lazy datasets in stream functions still remains. I believe there is not much we can do about it though.
