### ISSUE TITLE
Print log folder name after each epoch

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow#75]
I would like you opinion @petrbel and @blazekadam. I just don't remember the log folder name of each running training and sometimes I would like to go there to e.g., copy the model, check the results or whatever. Rolling up is sometimes impossible. I would like cxflow to print log folder name after each epoch (not necessarily log, only print) similarly to our old framework.

**Comment by petrbel** [comment]
I suggest writing a hook for that

**Comment by petrbel** [comment]
closed by #118
