### ISSUE TITLE
Allow to predict other streams or add `cxflow eval`

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow#76]
Cxflow predict is meant to evaluate raw data without the ground truth or training data.
However, currently, cxflow predict calls extra streams. This is unfortunate from multiple reasons:

1. It is the only way to evaluate valid and test streams. However, I would like to be able to evaluate valid and test streams without loading new data or implementing prediction stream.
2. I don't need to own the valid or training data in a production ready environment where predict is meant to be used. I know that valid and test streams can be skipped in the config, but still, it is not intuitive that `predict` calls `valid_stream` and `test_stream`.

Solutions:
The most obvious solution to both issues is to have two functions, e.g., `cxflow test` and `cxflow predict`. I am not sure about the name for `cxflow test`, since it runs `extra_streams`. `cxflow extra` does not sound proper either. Maybe we could rename `extra_streams` to `test_streams` or similar.

**Comment by blazekadam** [comment]
I agree. `cxflow predict` should iterate trough `predict` stream only.

Perhaps we can name the other command `cxflow eval` yet for v0.8, refactoring `predict` is enough.

**Comment by FloopCZ** [comment]
@petrbel's suggestion for the `cxflow predict <stream-name> <config>` looks good to me. See the discussion https://github.com/Cognexa/cxflow/pull/89#discussion_r135709274 for its pros and cons.

**Comment by petrbel** [comment]
@FloopCZ @blazekadam 
Note: the predict stream is currently used in two modes (with of without passed payload). Hence, @FloopCZ's point 2. is solved.

I think it's ok for now to evaluate other streams just by yielding them from the predict stream. Btw one can always make the predict stream look at some dataset config and use the proper stream (given by some config option).
