### ISSUE TITLE
Cxflow predict should be renamed

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow#81]
The word `predict` is confusing and relates to time series prediction. In our case, we only feed data into the network and use it for `inference`. We should probably rename `predict` to `infer` to be consistent with the current research.

**Comment by blazekadam** [comment]
Considering all the aspects, **I would go for it**. Imo the main point is that `predict` is indeed more bound to the future and time series while `infer` is more general...

**Comment by blazekadam** [comment]
@petrbel , @adkoadko , @MarekSebo please comment...

**Comment by petrbel** [comment]
I vote for **infer**

**Comment by adkoadko** [comment]
I like **predict** more, as Scikit-learn and Keras both have **predict**.

**Comment by blazekadam** [comment]
I **like** `predict` more yet `infer` seems to be more rational. 

Anyways I vote for `predict` now as Keras use it as well. Therefore, it is 2 v 2 at the moment.

Closing for now, we can re-open this discussion for 1.0 release.

**Comment by FloopCZ** [comment]
Good point @adkoadko, Keras and scikit-learn still use `fit` and `predict` (and `evaluate`). See [the docs](https://keras.io/models/sequential/). So we can use it as well.
